[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Handle SPA routing - redirect all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Netlify Identity
[[redirects]]
  from = "/.netlify/identity"
  to = "https://keweenaw-now.netlify.app/.netlify/identity"
  status = 200

[[redirects]]
  from = "/.netlify/identity/*"
  to = "https://keweenaw-now.netlify.app/.netlify/identity/:splat"
  status = 200

# Media uploads
[[redirects]]
  from = "/images/uploads/*"
  to = "/images/uploads/:splat"
  status = 200

# Admin panel
[[redirects]]
  from = "/admin/*"
  to = "/admin/"
  status = 200

# Enable CORS for Netlify CMS
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "ALLOW"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"