backend:
  name: git-gateway
  branch: main
  repo: your-username/your-repo-name
  site_domain: your-site.netlify.app

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "src/content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "publishDate", label: "Publish Date", widget: "datetime" }
      - { name: "description", label: "Description", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "tags", label: "Tags", widget: "list", allow_add: true }
      - { name: "featuredImage", label: "Featured Image", widget: "image" }